sudo: required
language: python
python:
  - "3.6"
before_script:
  - script/setup
  - script/server &
  - curl --connect-timeout 5 --retry 10 --retry-delay 2 --retry-connrefused 'http://localhost:8000'
script:
  - script/test
services:
  - postgresql
  - docker
env:
  - FLASK_ENV=ci
